### PR TITLE
Profile page, Control panel and viewer sidebar

### PR DESCRIPTION
**Pull request by Tawataka**
Added a resume migration, resume added to the user schema

### CODE REVIEW

**Comment by HiyabW** [comment]
Everything in the checklist works appropriately, signed in and signed out. The new design for the profile page and viewer sidebar looks really nice. Only potential concern would be that the edit profile page no longer aesthetically flows with any of the other pages within the control panel, but that can probably be handled in another pull request, and the functionality of it is still good.

**Comment by ece106** [comment]
Thank you, @HiyabW . Did you Read The Code also?

**Comment by HiyabW** [comment]
@ece106 Yes I read the code, I actually helped write it. And yes I uploaded a resume, it worked just fine on my end

**Comment by vietle2111** [comment]
All basic functions in the checklist are still working well.
The new design of profile page now looks really good, and all functions in Profile and Control Panel are working properly.
There are some concerns:
- After filling information in Sign Up page, then Submit, it redirects to user/profileinfo page without email confirmation. This is currently happening on ThinQ.tv website too.
- In Control Panel, if I upload my resume as .docx or other extensions, the flash error message is shown but behind the menu bar, so I can’t see what the error message is. Also users need to know that only PDF is accepted. This can be improved in next pull requests.

**Comment by ece106** [comment]
@Tawataka This needs to be corrected before any test branch will be accepted: CLEARLY indicate that resumes may only be uploaded as pdf OR allow .doc files also. I suggest allowing .doc, .docx 

@vietle2111 , what are you referring to about email confirmation?

**Comment by vietle2111** [comment]
We normally receive an email with a link to active a new user after registering, unless that new user account will be not allow to sign in. In this case, I don’t even need to activate but still able to log in.

**Comment by ece106** [comment]
I disabled confirmations.

**Comment by selenali07** [comment]
Tested all the functionality in the checklist and most of the basic functions run smoothly. 
- Having issues uploading resume with docx, and if it is restricted to only pdf you should make a note of it.
- Theres a red box that pops up after submitting sign up information but no error or confirmation message?
- When you upload resume in the wrong format and press submit, it does not save/submit other information.

Also couple of minor issues/points:
- Is it possible to put an edit profile option on the view profile page for accessibility?
- "What Skills or Interest best define you?" pre fill text box is that interest is spelled wrong.
- Padding for in Manage Rewards is inconsistent with the rest of control panel.
- The overall grid system layout is not the prettiest.

**Comment by ece106** [comment]
Please address Selena's comments. 
I would place "The overall grid system layout is not the prettiest" in the Basic Functions category. Not a minor issue.

**Pull request merged**
