### PR TITLE
Fixed a syntax error that snuck in after pulling from master

### PR DESCRIPTION
**Pull request by snowylily**

### CODE REVIEW

**Comment by pth051001** [comment]
Control_panel_events_list test works now. Should be merged to master.

**Comment by vietle-testing** [comment]
Can't edit a created DropIn/Conversation in View Profile page.
An error is shown as: ActionView::SyntaxErrorInTemplate in EventsController#edit

**Comment by snowylily** [comment]
Are you sure you've pulled the latest version and not the previous one? This is exactly what the latest commit was meant to fix.

**Comment by vietle-testing** [comment]
No error is found in Control Panel page, all functions work properly.

**Pull request merged**
