### PR TITLE
Added more tests to test the purchases section of the application.

### PR DESCRIPTION
**Pull request by prachiMiyan**

### CODE REVIEW

**Comment by roberthaas47** [comment]
Got 6 fails and 16 errors. Localhost seems to be working fine

**Comment by Andralizer** [comment]
When running rails test: 303 runs, 392 assertions, 6 failures, 16 errors, 0 skips

No noticeable issues as such.

**Comment by prachiMiyan** [comment]
I'm not getting any errors. What exactly do the errors state?

**Comment by prachiMiyan** [comment]
Run tests only for purchases controller test and purchases tests in
integration tests. Those are the tests that I have added.

**Comment by ece106** [comment]
I'm going to guess that the errors have something to do with invalid Stripe keys.

**Comment by prachiMiyan** [comment]
Hi Lisa,

I'm not getting any errors, else I wouldn't have made a pull request. I'll
run all the tests for you and show you the results tomorrow, at work.

Regards,
-Prachi Miyan

**Comment by ece106** [comment]
Perhaps Prachi isn't getting errors, but other people are because they have not earned the right to Stripe keys.

**Comment by prachiMiyan** [comment]
That's probably correct. I'll look at what errors Robert is getting and see
what exactly the problem is.

**Pull request merged**
