### PR TITLE
Resume allows pdf, doc and docx

### PR DESCRIPTION
**Pull request by Tawataka**
Also added subtitle under resume upload section stating what file types are allowed.

### CODE REVIEW

**Comment by vietle2111** [comment]
- All functions in the checklist work appropriately.
- Subtitle is added for file types which allowed in resume (doc, docx, pdf)
- If uploading some file types not in doc, docx or pdf. The flash error box shows with no message/content. The flashing error message should be improved.

**Comment by beverlyperez** [comment]
0. Nothing entered seemed sloppy 
1. Sign Up works 
2. Sign In works 
3. Monthly view does not show the past events, only future and present. Daily view and the users conversations tab shows past events.
4. View profile page cuts off one image
5. Profile section of controlpanel works
            a. Changes are saved
            b. Was able to connect to Stripe
            c. Was able to upload images and save changes
6. Was able to create Buy and Donate rewards with pictures and descriptions
7. control panel page works
8. Email, password, and url changes saved
9. Can purchase, donate, and add a new card in the sales section
10. View profile page works
11. Links in footer works
12. Signed out and did everything again. Still the same results
13. Still cannot connect localhost on my phone

**Comment by snowylily** [comment]
- There is a typo in the sample text for interests/skills when editing the user profile (inrerest)
image
- Uploading pdf and doc/docx resumes works; as Viet said there is no error message when uploading the wrong format

**Comment by snowylily** [comment]
image
image
Events list and homepage heroImage are significantly cut off on mobile

**Comment by snowylily** [comment]
that was the events list under user profile, sorry for the ambiguity
Here's the homepage
image

**Pull request merged**
