### PR TITLE
Bootstrapfinal test

### PR DESCRIPTION
**Pull request by kmyee97**
**Purpose**
Migrating to **Bootstrap 4** from **Bootstrap-sass 3.4.1**
Fixed faq 
Added images as requested by Lisa in app/views/static_pages/drschaeferspeaking.html.erb

### CODE REVIEW

**Comment by vinhnguyen200891337** [comment]
All the buttons and links work well. However, spacing is still an issue. At footer, might need a little bit more padding to the left. In home page the space between header and footer the the boxes are a little bit too wide. Also minimize the space between the background group photo and increase the padding in the Why ThinQ.tv in the aboutus page. Also in the jointheteam, you should reduce the size of "Experience What We're Doing" box. You also should make sure there is only 1 kind of design for the drop boxes in the both dropin and jointheteam. You might need to fix the dropdown of the so that is the right color and spacing. In the control panel, you should align the two button so that they are center, not to the left. You might need to fix the navbar in the controlpanel so that it matches with the one on ThinQ.tv. Sorry if it sounds like nit-picking.

**Comment by vinhnguyen200891337** [comment]
Overall the site is good, it just has a lot of small mistakes that doctor Schaefer might not like, that's all

**Comment by snowylily** [comment]
### Checklist:
1. ok
2. ok
3. ok
4. ok
5. ok
6. ok
7. ok
8. ok
9. ok
10. ok
11. ok

### Observations:
Globally
The background-color for body is now pure white versus #F0F0F0 as it was before (might be to eliminate the double scrollbars?). It looks odd to me but that might be because I'm used to the slightly off-white background.

/getinvolved
Margins and alignments are messed up on Why ThinQ.tv? on desktop, see screenshot.
getinvolved-1


/studyhall
Monthly view calendar is really thin when empty, see screenshot.
Still says "We currently have Activism Halls for 3 topics" instead of drop-in hours.
studyhall-2


/profileinfo
CSS looks a little wonky in some places (spacing and font sizes "We're talking about TestPresent right NOW!")
profileinfo-1

/drschaeferspeaking
Looks much better than before.

Homepage
Countdown timer still looks really ugly.
home-1

Mobile
"New to ThinQTV?" text gets cut off on homepage
image

Upcoming Conversations cut off on mobile
image (1)

Spacing in /getinvolved (About Us) with icons all kinds of wonky on mobile
image (2)

### Conclusion:
Everything works, but a lot of CSS needs adjustment.

**Comment by snowylily** [comment]
Also this dropdown got messed up
Before:
image

After:
image

**Pull request merged**
