### PR TITLE
Stats

### PR DESCRIPTION
**Pull request by RogelioMart**
This new feature records the the time in and time out of each user when they go into a chatroom. The data is saved into an sql table named attendances. A normal user cannot see this information in order to test this new feature you need to query your sql database.

To access your database (sometimes username is not necessary)
`psql -d <DEVELOPMENT DATABASE NAME> -U <USERNAME>`

To display the tables in the database, check that attendances is listed there.
`\d`
`
Display all the rows in the attendances table.
`SELECT * FROM attendances;`

Display all the time ins and time outs of a specific user based on id number.
`SELECT * FROM attendances WHERE user_id = <user's id number>;`

Display all the time in and time outs from all the users for s specific event.
`SELECT * FROM attendances WHERE event_id = <the event's id number>;`

I recommend you use the following queries and check the expected results. I also encourage you to make your own queries to properly test my branch. (ALL of the following queries measure the time in MINUTES.)

```
--find total time the user has spent in conversations based on their permalink
  SELECT SUM(EXTRACT (minute FROM time_out - time_in)) AS total_time 
  FROM attendances A, users U
  WHERE A.user_id = U.id AND U.permalink = '<user's permalink>';

--find the interval time a user has spend in conversations.
--reminder SQL time stamp follows the following format 2020-08-06 21:48:23.0 (YYYY-MM-DD HH:MM:SS.0)
  SELECT SUM(EXTRACT (minute FROM time_out - time_in)) AS interval_time 
  FROM attendances A, users U 
  WHERE A.user_id = U.id AND U.permalink = '<user's permalink>' AND A.time_in > 'YYYY-MM-DD HH:MM:SS.0' AND A.time_out < 'YYYY-MM-DD HH:MM:SS.0';

--find total time a specific user spent in a specific conversation based on their permalink and the event's id
  SELECT SUM(EXTRACT (minute FROM time_out - time_in)) AS total_time_in_event 
  FROM attendances A, users U
  WHERE A.user_id = U.id AND U.permalink = '<user's permalink>' AND A.event_id = <id number for event>;

```

### CODE REVIEW

**Comment by brobs0111** [comment]
New attendance table looks good and is populating with the correct information. The only issue is if you click the Red end call button and then exit chat it doesn't populate a time for time_out it remains null. However when you exit the page instead of ending the call it populates the time_out variable. This appears to be due to the same reason attendees don't always show as being gone when they leave. 

Changes did not break anything. I'd say it is good to go, just need to refine so that it always tracks user's leaving.

**Comment by ece106** [comment]
Part of this will be solved with Abe & Andersons debugging of the Attendees list.

**Comment by kmyee97** [comment]
The attendance table works for conversations, drop-ins, group problem solving, and recurring events. The table populates the time_in cell when the user enters the view page for that particular event. Moreover, it populates the time_out cell when the user exits the view page for that particular event. 

However, as brobs0111 said, the time_out cell does not fill when a user clicks the Leave Button in Jitsi. Needs work.

Besides that, the new addition works and it’s ok to merge to master.

**Comment by pth051001** [comment]
Localhost checklist passed.
The attendance table works for all types of events and populates the time_in and time_out cell when entering or exiting the the page. The only issue that I got is the same as Blake and Kahlil, which is about the leave button (not saving the time_out cell).
However, I think this branch should be merged since, as Lisa said, that problem will be solved later.

**Pull request merged**
