### PR TITLE
Cleaned up CSS

### PR DESCRIPTION
**Pull request by HiyabW**
Deleted all css files but main and application. Condensed all previous css into main (and kept application because the site wouldn't work without it). Then I deleted any unused/unnecessary CSS. This also resulted in very minor aesthetic changes to home, events page and merchandise page.

### CODE REVIEW

**Comment by ece106** [comment]
Why is this worth a pull request? 
It looks like you deleted a bunch of scss and pasted it into 1 file. How are the styles consolidated & cleaned up? Why is there a td and th style? What are all the tabcontainers for? All the uls? 
What is this 
#suggestedPerks {
  margin-top: 20px;
}
Are any of the profilethings used? 
Do we need this 
#merchSidebar {
  max-height: 75vh;
  overflow-y: scroll;
}

//Perk display
#perkImage {
  height: 100px;
  width: 100px;
  object-fit: cover;
}

**Comment by HiyabW** [comment]
I relocated all the CSS into one file and deleted what wasn't being used. I
tried organizing it in such a way that the top half of the file (main) is
the globals/what is used throughout the site (header, footer, fonts,
body... these are used in all pages). Then, I have the specific CSS for
each page (for example, the countdown clock is only used on the homepage,
which is why its under the section I labeled "home")

Concerning some of your suggestions:

   - the th/td is used for the calendar. I can try to trim a few lines from
   it, but it has to stay or else the calendar view for the events will
   disappear.
   - the tab containers are for the buttons for the Drop in section of the
   home page. I was able to trim some stuff for that section, but for the most
   part the page will get messed up if I take too much out.
   - the ul/li are for the FAQ page, it has a lot of special css. In fact,
   it used to be a bit longer, what you see is the trimmed down version
   - we need most of the profile things, they are being used and
   significantly mess up the page when removed
   - the merch side bar was being used for the old profile page, but now
   that tawa updated it i took them out.


I thought the purpose of this pull request was supposed to be a step
forward so people could at least have easier access / descriptions to the
stylesheets, not necessarily a finished product. Its hard to have
veerything consistent when each page is doing its own thing, but I took my
time and deleted a lot more stuff since your email, hopefully it looks a
little better.

**Comment by Tawataka** [comment]
Nothing necessary seems to be deleted. It looks like a lot of unnecessary code was removed and trimmed. I do believe that once all unnecessary code is removed it should be separated into separate files for easy access and organization.

**Comment by vietle2111** [comment]
- All functions in the checklist are working properly. 
- Cleaning up css does not affect on functionalities, but there are some changes on text size in some place compare to the current website:
+ In Homepage, at Mentor Hours, Daily View tab: conversation titles look so small.
+ In Profile page, in convo attending list: conversation titles look so small.

**Pull request merged**
