### PR TITLE
Mailers

### PR DESCRIPTION
**Pull request by PLgitdev**
User and event mailers created. These mailers have tests and views and previews. 4 mailers in the user mailer are triggered by the purchase controller when a user makes a purchase or donation. In the User mailer there is also a Welcome Mailer triggered by the create user method in the user controller. The create event method also triggers a timed mailer to remind a user about their created event 2 days before that event starts.

### CODE REVIEW

**Comment by wujason1** [comment]
Tested mailers code, rails test got 7 failures, 19 errors. An error was found when purchasing a reward, but it should just be a localhost error.

**Comment by ece106** [comment]
But DO THE MAILERS WORK????

**Comment by roberthaas47** [comment]
When running rails test I got 6 fails and 17 errors, one fail was from event_mailer_test. It looks like he just put down the wrong email. Everything on localhost seems to be working fine except when I try to purchase an item from another user. I get ActiveRecord::RecordNotFound in PurchasesController#create. I don't know if this is because of localhost or not, but I though I should just mention this.

**Comment by wujason1** [comment]
Based on the function tests in user and purchase controller tests, mailers is working. But, it doesnt seem to be working on localhost.

**Comment by ece106** [comment]
Don't just mention it, DIAGNOSE, FIX.

**Comment by roberthaas47** [comment]
I got 6 fails and 17 errors when running rails test, none seem to be from Peter. Mailers worked for me, I got emails for creating events, creating a new user, and making donations. However, I was not able to make purchases. I could only make donations if they were the default donations. I will provide a screenshot of the error I get when trying to purchase an item. Other than that everything seems to be working fine

**Pull request merged**
