### PR TITLE
Newtest

### PR DESCRIPTION
**Pull request by aanchalcoder18**
minor errors fixed -ignore images they are a little to the left

### CODE REVIEW

**Comment by danielgoncalves25** [comment]
need a link to conversation/drop-in under the countdown clock

**Comment by ece106** [comment]
Could you be more specific

**Comment by ece106** [comment]
The countdown clock is only shown when there is no conversation/drop-in in progress. If there's no chatroom open, what do you want the link to go to

**Comment by danielgoncalves25** [comment]
when no conversation/drop-in is live, under the countdown clock, the event name for next conversation/drop-in need a link to the event show page and host name needs a link to hosts show page

**Comment by danielgoncalves25** [comment]
also, when a conversation/drop-in is live, the join conversation/drop-in button is disabled.

**Comment by ece106** [comment]
Why can't we have goddamn buttons that work

**Comment by vinhnguyen200891337** [comment]
The space between the header and the background is a little bit wide. When problem solving, conversation and dropin appear all at the same time, the problem solving button overlap with the office meeting picture on the right. The caption underneath the picture needs to move a little bit to the left to center. I am going to assume that the buttons to the conversation is going to be clickable later in the future because they are a back-end thing. Sorry if it is a little bit picnicking.

**Comment by ece106** [comment]
THERE ARE MERGE ERRORS ALL OVER THE GET INVOLVED AND DR SCHAEFER SPEAKING PAGES!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by danielgoncalves25** [comment]
In the home.html.erb file, the join conversation button under the countdown clock is being rendered from this line of code.
<%= render 'layouts/countdown_clock' %>

and the join drop-in button under the countdown clock is being rendered from this line of code
<%= render 'layouts/countdown_clockstudy' %>

in _countdown_clock.html.erb, the conversation button is on the 7th line
in _countdown_clockstudy.html.erb, the drop button is on the 8th line

**Comment by ece106** [comment]
Line 9 of countdown_clock does not have a method to a path. Please look at how links are constructed in the rest of the repository.

**Comment by ece106** [comment]
Are you sure the buttons don't work? I don't see any change that would've broken the buttons.

**Comment by ece106** [comment]
Um, no, @vinhnguyen200891337 we don't put broken buttons on the home page leaving no one able to Join Conversation (The Whole Purpose Of The Site) then make them work later.

**Pull request merged**
