### PR TITLE
About Us and Sign Up padding

### PR DESCRIPTION
**Pull request by mickarnold36**
updated the about us page, fixed the margin error on sign up page, updated and resized the icons

### CODE REVIEW

**Comment by snowylily** [comment]
1) Sign up page looks good on desktop and mobile
2) The mobile About Us page looks much better overall with the new icons (see video: https://streamable.com/uk1itx), however:
- the margins under "Join in Activism..." are now significantly narrower than need be, causing awkward line breaks and hindering readability
- margins and text alignments are inconsistent (compare "Join in Activism..." to "Our Story" in video)

**Comment by ece106** [comment]
Hey, how did you make this Streamable thing

**Comment by snowylily** [comment]
1) rails s -b 0.0.0.0 so I could connect to the site locally from my phone over wifi
2) Recorded using iOS Screen Recording (you can add to your Control Center under Settings -> Control Center -> Customize Controls)
3) Sent the mp4 to myself on Discord in a private server, cropped with ffmpeg, uploaded to streamable.com

**Comment by ece106** [comment]
How do you access from phone

**Comment by snowylily** [comment]
http://[host IP]:3000 in the URL bar

**Comment by ece106** [comment]
If [host IP] = 0.0.0.0 or localhost, I already tried both of those & neither worked.

**Comment by snowylily** [comment]
[host IP] is the private IP assigned by the network to the machine running the server, in my case it's a 10.x.x.x address but it could also be 192.x.x.x. Under Windows you can get this IP via ipconfig in cmd, under Linux or Mac it's ifconfig in a terminal. Both the phone and the computer need to be connected to the same wireless network for it to work.

**Comment by ece106** [comment]
ifconfig didn't work, but 
dig +short myip.opendns.com @resolver1.opendns.com
gave me an IP. I tried it on my phone & it doesn't access anything. I tried it again on another device that's missing a phone card (so I know it's using the same wifi) but that doesn't access my laptop server either.

**Comment by snowylily** [comment]
The IP you get with that dig command is your public IP, not your private/local IP. You need the local one assigned to your laptop's wireless interface/NIC. Did ifconfig not give you any output at all?

On my Linux laptop, ifconfig output gives me information on three interfaces:
enp8s0 (Ethernet) (not the one I want)
lo (loopback, aka localhost) (also not the one I want)
wlp9s0 (wireless) (the one I want, and the address I specifically want is the one labeled "inet")

Assuming you're on a Mac, you could try this:
https://www.macworld.co.uk/how-to/mac/ip-address-3676112/#toc-3676112-5

**Comment by ece106** [comment]
Linux
I had to sudo apt install net-tools before ifconfig would work.
The wlp9s0 IP address worked!

**Comment by ece106** [comment]
Could you put a note about this in the TEST channel of discord so all the front end developers can see the site on mobile before making pull requests?

**Comment by snowylily** [comment]
My mistake, shouldn't have assumed it'd be there by default. It's been a long time since I installed net-tools.
Will do!

**Comment by vinhnguyen200891337** [comment]
All the pages look right except the drschaeferspeaking page. There are two pictures. Also you should have one style of drop down on the Studyhall and Jointheteam.

**Pull request merged**
