### PR TITLE
Footer is ready to test

### PR DESCRIPTION
**Pull request by eedelosreyes2**
Haven't tested Open Graph tags on localhost because they cannot be tested locally. If Open Graph tags are grabbed correctly from` _favicon.html.erb` then should be working as intended.

### CODE REVIEW

**Comment by wujason1** [comment]
299 runs, 383 assertions, 6 failures, 19 errors, 0 skips after testing the footer code
The website works fine. A small error I found was that when you click the name of the show, there are two button to edit the show. They both go to the same view. Should remove one of the buttons.

**Comment by ece106** [comment]
Yeah, I mentioned those double Edit links to Amy. She says she deleted them for her next pull request.

**Comment by ece106** [comment]
Why are there more failures than there used to be?

**Comment by Andralizer** [comment]
This is what I got: 
298 runs, 383 assertions, 6 failures, 18 errors, 0 skips.

Footer section works fine on the website.

**Pull request merged**
